In [2]:
import os
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

from tqdm import tqdm
from sklearn.cluster import AgglomerativeClustering

In [3]:
class ImageToArray():
    def __init__(self):
        pass

    def action(self, path):
        image = mpimg.imread(path)
        np_img = np.array(image)
        np_img = np_img.flatten()
        return np_img

In [10]:
animal_list = ['cat', 'lion', 'leopard', 'tiger', 'jaguar', 'sphynx', 
                'dog', 'wolf', 'husky', 'corgi', 'pug']

dataset = []
directory = './Data/'

for animal in tqdm(animal_list):
    folder = directory + animal
    for image in os.listdir(folder):
        filename = folder + '/' + image
        imageToArray = ImageToArray()
        imageFlatten = imageToArray.action(filename)
        dataset.append(imageFlatten)

dataset

100%|██████████| 11/11 [00:00<00:00, 16.49it/s]


[array([77, 77, 76, ..., 75, 75, 74], dtype=uint8),
 array([56, 58, 64, ..., 19, 18, 17], dtype=uint8),
 array([193, 193, 192, ..., 149, 149, 149], dtype=uint8),
 array([170, 169, 168, ..., 188, 183, 181], dtype=uint8),
 array([22, 22, 22, ..., 52, 51, 51], dtype=uint8),
 array([ 6,  6,  6, ..., 31, 28, 26], dtype=uint8),
 array([ 35,  35,  33, ..., 231, 225, 219], dtype=uint8),
 array([147, 147, 147, ...,  25,  27,  29], dtype=uint8),
 array([92, 93, 94, ..., 83, 85, 83], dtype=uint8),
 array([105, 105, 105, ...,  83,  82,  82], dtype=uint8),
 array([199, 200, 199, ...,  68,  67,  67], dtype=uint8),
 array([121, 123, 125, ..., 209, 206, 203], dtype=uint8),
 array([0, 0, 0, ..., 0, 0, 0], dtype=uint8),
 array([45, 45, 46, ..., 42, 42, 42], dtype=uint8),
 array([200, 199, 197, ..., 204, 203, 203], dtype=uint8),
 array([ 23,  25,  28, ..., 247, 247, 247], dtype=uint8),
 array([180, 180, 180, ..., 175, 175, 175], dtype=uint8),
 array([165, 166, 167, ..., 130, 130, 130], dtype=uint8),
 arr